/*
 * config.h — Build-time platform configuration
 * Auto-generated by Makefile; do not edit.
 */
#ifndef NOVDB_CONFIG_H
#define NOVDB_CONFIG_H

#define NVDB_PAGE_SIZE           8192
#define NVDB_PAGE_HEADER_SIZE    40
#define NVDB_MAX_KEY_SIZE        2048
#define NVDB_BUFFER_POOL_SIZE    4096
#define NVDB_IDENTIFIER_MAX      128
#define NVDB_DEFAULT_PORT        9876
#define NVDB_MAX_CONNECTIONS     1024
#define NVDB_WAL_SEGMENT_SIZE    16777216

#if defined(__linux__)
#define HAVE_EPOLL    1
#else
#define HAVE_EPOLL    0
#endif

#define HAVE_PREAD    1
#define HAVE_PWRITE   1
#define HAVE_MMAP     1
#define HAVE_FCNTL    1

#if defined(__linux__)
#define HAVE_FALLOCATE 1
#else
#define HAVE_FALLOCATE 0
#endif

#define HAVE_FADVISE  0

#if defined(__linux__)
#define HAVE_BYTESWAP_H 1
#else
#define HAVE_BYTESWAP_H 0
#endif

#if defined(__linux__)
#  define NVDB_PLATFORM_LINUX 1
#elif defined(__APPLE__)
#  define NVDB_PLATFORM_MACOS 1
#elif defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
#  define NVDB_PLATFORM_BSD 1
#endif

#endif /* NOVDB_CONFIG_H */
